spring.application.name=notification-service
server.port=8088

spring.kafka.bootstrap-servers=localhost:29092
spring.kafka.consumer.group-id=notification-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.listener.auto-startup=true

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JacksonJsonDeserializer

spring.kafka.consumer.properties.spring.json.trusted.packages=com.prilepskiy_ae.common

spring.kafka.consumer.properties.spring.json.value.default.type=com.prilepskiy_ae.common.UserEventDto
app.kafka.topic.user-events=user-events

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_LOGIN}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

app.mail.from-address=${MAIL_LOGIN}
app.mail.site-url=https://example.com
