spring.application.name=gateway-service
server.port=8080

gateway.services.user-service-url=http://localhost:8081
gateway.services.notification-service-url=http://localhost:8082

resilience4j.circuitbreaker.instances.userServiceCircuitBreaker.slidingWindowSize=10
resilience4j.circuitbreaker.instances.userServiceCircuitBreaker.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.userServiceCircuitBreaker.automaticTransitionFromOpenToHalfOpenEnabled=true
resilience4j.circuitbreaker.instances.userServiceCircuitBreaker.waitDurationInOpenState=10000
resilience4j.circuitbreaker.instances.userServiceCircuitBreaker.failureRateThreshold=50


resilience4j.circuitbreaker.instances.notificationServiceCircuitBreaker.slidingWindowSize=10
resilience4j.circuitbreaker.instances.notificationServiceCircuitBreaker.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.notificationServiceCircuitBreaker.automaticTransitionFromOpenToHalfOpenEnabled=true
resilience4j.circuitbreaker.instances.notificationServiceCircuitBreaker.waitDurationInOpenState=10000
resilience4j.circuitbreaker.instances.notificationServiceCircuitBreaker.failureRateThreshold=50
