server.port=8888
spring.application.name=config-server

spring.profiles.active=native
spring.cloud.config.server.native.search-locations=file:./config
spring.cloud.config.server.git.clone-on-startup=true